### ISSUE TITLE
Blacked out display after update

### ISSUE THREAD

**Issue by notmike-5** [brackeen/calculate-widget#1]
I updated to 1.2.2 and it blacked out my display to where I can't see shit. Fix it, Jesus!
<img width="301" alt="screen shot 2017-09-07 at 7 57 49 pm" src="https://user-images.githubusercontent.com/16808272/30191529-ec2d074c-9406-11e7-9025-3df34e3a9d1e.png">

**Comment by brackeen** [comment]
Hey thanks for the heads up. What versions of Mac OS X and Safari do you have?

**Comment by notmike-5** [comment]
oooooh... nice avatar!

Running Sierra 10.12.6. I don't even know if I have Safari.

Plot twist: Safari 10.1.2

**Comment by brackeen** [comment]
Weird. I'm running the same versions, and have no problem with the display. Try `killall Dock`, or uninstall/reinstall?

**Comment by notmike-5** [comment]
`killall Dock` did the trick
