### ISSUE TITLE
Create a native version

### ISSUE THREAD

**Issue by brackeen** [brackeen/calculate-widget#2]
The next version of macOS (Catalina) will remove the dashboard. Create a version of Calculate that uses the same JavaScript engine but with a native UI. 

Also explore additional features:
- [ ] ~An option to hide the dock icon~ Not possible to have a menu bar with no dock icon
- [ ] ~Appear on top of full-screen apps~ Not possible
- [x] Quick launch button (F5 or customizable key combo)
- [x] If possible, on first launch, import old saved variables/functions from the widget.

**Comment by theshadow27** [comment]
Alternatively (or in addition) - could it be built into notification center like the Apple Calculator?

**Comment by hansbihs** [comment]
Very much missing the calculate widget on Catalina...just wondering whether there is there any development ongoing on bringing it back?

**Comment by brackeen** [comment]
@hansbihs Yes. It is a priority for me personally (I use Calculate every day, haven't updated to Catalina yet), although I don't have a timeframe yet.

**Comment by theshadow27** [comment]
I looked into this briefly to see if I could help (I haven't updated yet either, holding on to a few other dependencies including Calculate), basically would need to create an AppStore app (means signing, etc), which can hide itself/minimize to menu bar, and a notification center "Today" integration to kind of get where the widget is today. The implementation is pretty easy, an embedded web view that runs the existing code, though there are pretty strict CPU/memory requirements which can result in the plugin being terminated. It was all above my head. 

Newer versions of BTT support transparent HTML popups ( see https://folivora.ai/blog/post/13000 ), might be an easier port from the widget version.

**Comment by brackeen** [comment]
A first alpha of a native version is now downloadable here: https://github.com/brackeen/calculate-widget/releases/tag/2.0-alpha-1

If you run into problems please open a new issue or email me directly, thanks!

**Comment by hansbihs** [comment]
Hi David,

great to see this, thanks a lot!

Cheers
Hans


_________________________________________________________
Hans Bihs
hans.bihs@gmail.com

Trondheim, Norway
Phone: +47 905 81 674
